name: cached_network_image
description: Flutter library to load and cache network images.
  Can also be used with placeholder and error widgets.
publish_to: none
# homepage: https://github.com/Baseflow/flutter_cached_network_image
# topics:
#   - cache
#   - image
#   - network-image
version: 3.3.0
environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  # cached_network_image_platform_interface:
  #   path: packages/cached_network_image_platform_interface/
  # cached_network_image_web:
  #   path: packages/cached_network_image_web/
  flutter:
    sdk: flutter
  flutter_cache_manager:
    git:
      url: https://github.com/Yuvaraja-K/flutter_cache_manager.git
      ref: main
  octo_image: ^2.0.0

dev_dependencies:
  file: ">=6.1.4 <8.0.0"
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
